steps:
  # 1. Constrói a imagem Docker aplicando a tag do Commit e a tag 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/homilia-app-repo/free-homilia-app-br:$COMMIT_SHA'
      - '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/homilia-app-repo/free-homilia-app-br:latest'
      - '.'

  # 2. Envia as imagens para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/homilia-app-repo/free-homilia-app-br:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/homilia-app-repo/free-homilia-app-br:latest']

  # 3. Faz o deploy no Cloud Run usando a imagem estável gcloud oficial
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:stable'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'free-homilia-app-br'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/homilia-app-repo/free-homilia-app-br:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'APP_ENV=production,LOG_CHANNEL=stderr,SESSION_DRIVER=cookie,CACHE_STORE=file,APP_DEBUG=false'

options:
  logging: CLOUD_LOGGING_ONLY