# user www-data;
# events {}
# http {
#     include /etc/nginx/mime.types;

#     server {
#         # Cloud Run injeta a variável de ambiente PORT
#         listen 8080;
#         server_name _;
#         root /var/www/html;
#         index index.php;

#         location / {
#             try_files $uri $uri/ /index.php?$query_string;
#         }

#         location ~ \.php$ {
#             fastcgi_pass unix:/var/www/html/run/php-fpm.sock;
#             fastcgi_index index.php;
#             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#             include fastcgi_params;
#         }

#         # Otimizações
#         location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
#             expires 1y;
#             log_not_found off;
#         }
#     }
# }

server {
    listen 80;
    root /var/www/html;
    index index.php index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}